import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const file=root=>path.join(root,'campaigns.json');
const read=root=>{try{return JSON.parse(fs.readFileSync(file(root),'utf8'))}catch{return {version:1,campaigns:[]}}};
const write=(root,state)=>{fs.mkdirSync(root,{recursive:true});const f=file(root),tmp=f+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state,null,2),{mode:0o600});fs.renameSync(tmp,f);return state};
const channels=new Set(['youtube-shorts','youtube','tiktok','instagram-reels','instagram','website','email','product']);
const cleanKpis=x=>{const v=x&&typeof x==='object'?x:{};return {views:Math.max(0,Number(v.views||0)),watchMinutes:Math.max(0,Number(v.watchMinutes||0)),published:Math.max(0,Number(v.published||0))}};
export function listCampaigns(root){return read(root).campaigns||[]}
export function getCampaign(root,id){return listCampaigns(root).find(x=>x.id===id)||null}
export function createCampaign(root,input={}){const name=String(input.name||'').trim().slice(0,140);if(name.length<3)throw Error('campaign name is required');const selected=[...new Set((Array.isArray(input.channels)?input.channels:[]).map(String).filter(x=>channels.has(x)))];const startAt=input.startAt&&Number.isFinite(Date.parse(input.startAt))?new Date(input.startAt).toISOString():new Date().toISOString(),endAt=input.endAt&&Number.isFinite(Date.parse(input.endAt))?new Date(input.endAt).toISOString():null;if(endAt&&Date.parse(endAt)<Date.parse(startAt))throw Error('campaign end must be after start');const item={id:crypto.randomUUID(),name,goal:String(input.goal||'').trim().slice(0,600),channels:selected.length?selected:['youtube-shorts'],startAt,endAt,status:'planning',projectIds:[],assetIds:[],kpis:cleanKpis(input.kpis),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const state=read(root);state.campaigns=[item,...state.campaigns].slice(0,200);write(root,state);return item}
export function updateCampaign(root,id,patch={}){const state=read(root),item=state.campaigns.find(x=>x.id===id);if(!item)throw Error('campaign not found');if(patch.status&&['planning','active','paused','complete'].includes(patch.status))item.status=patch.status;if(patch.goal!==undefined)item.goal=String(patch.goal||'').trim().slice(0,600);if(Array.isArray(patch.projectIds))item.projectIds=[...new Set(patch.projectIds.map(String).filter(Boolean))].slice(0,200);if(Array.isArray(patch.assetIds))item.assetIds=[...new Set(patch.assetIds.map(String).filter(Boolean))].slice(0,200);if(patch.kpis!==undefined)item.kpis=cleanKpis(patch.kpis);item.updatedAt=new Date().toISOString();write(root,state);return item}
export function campaignMetrics(campaign,projects=[]){const linked=(campaign.projectIds||[]).map(id=>projects.find(x=>x.id===id)).filter(Boolean),complete=linked.filter(x=>x.status==='complete'),ready=complete.filter(x=>x.qa?.launchReady===true),approved=complete.filter(x=>x.publishApproval?.status==='approved');return {linkedProjects:linked.length,complete:complete.length,launchReady:ready.length,approved:approved.length,readinessRate:linked.length?Number((100*ready.length/linked.length).toFixed(1)):0,approvalRate:linked.length?Number((100*approved.length/linked.length).toFixed(1)):0}}
export function campaignSchedule(campaign,calendar={jobs:[],conflicts:[]},{slots=5}={}){const start=Math.max(Date.now(),Date.parse(campaign.startAt||new Date())),end=campaign.endAt?Date.parse(campaign.endAt):start+14*86400000,count=Math.max(1,Math.min(30,Number(slots||5))),step=Math.max(6*3600000,(end-start)/Math.max(1,count));const occupied=(calendar.jobs||[]).map(x=>Date.parse(x.scheduledAt)).filter(Number.isFinite);const suggestions=[];for(let i=0;i<count;i++){let at=start+i*step;for(let tries=0;tries<12&&occupied.some(t=>Math.abs(t-at)<30*60000);tries++)at+=60*60000;suggestions.push({index:i+1,scheduledAt:new Date(Math.min(at,end)).toISOString(),channels:campaign.channels})}return {campaignId:campaign.id,suggestions,conflictsDetected:(calendar.conflicts||[]).length,autoPublish:false,ownerApprovalRequired:true}}

export function campaignKpiProgress(campaign,performance={top:[]},publishJobs=[]){const ids=new Set(campaign.projectIds||[]),rows=(performance.top||[]).filter(x=>ids.has(x.projectId)),actual={views:rows.reduce((n,x)=>n+Number(x.views||0),0),watchMinutes:rows.reduce((n,x)=>n+Number(x.watchMinutes||0),0),published:publishJobs.filter(x=>ids.has(x.projectId)&&x.status==='published').length},target=cleanKpis(campaign.kpis);const pct=(a,t)=>t?Math.min(999,Number((100*a/t).toFixed(1))):null;return {target,actual,progress:{views:pct(actual.views,target.views),watchMinutes:pct(actual.watchMinutes,target.watchMinutes),published:pct(actual.published,target.published)},observedProjects:rows.length,policy:{observedMetricsOnly:true}}}
