import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const file=root=>path.join(root,'channel-goals.json');
const read=root=>{try{return JSON.parse(fs.readFileSync(file(root),'utf8'))}catch{return {version:1,goals:[]}}};
const write=(root,s)=>{fs.mkdirSync(root,{recursive:true});const f=file(root),t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(s,null,2),{mode:0o600});fs.renameSync(t,f);return s};
const metrics=x=>({views:Math.max(0,Number(x?.views||0)),watchMinutes:Math.max(0,Number(x?.watchMinutes||0)),published:Math.max(0,Number(x?.published||0)),subscribers:Math.max(0,Number(x?.subscribers||0))});
export function listChannelGoals(root){return read(root).goals||[]}
export function createChannelGoal(root,input={}){const name=String(input.name||'').trim().slice(0,120);if(name.length<3)throw Error('goal name is required');const item={id:crypto.randomUUID(),name,platform:String(input.platform||'all').slice(0,40),niche:String(input.niche||'all').slice(0,60),target:metrics(input.target),status:'active',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const s=read(root);s.goals=[item,...s.goals].slice(0,100);write(root,s);return item}
export function updateChannelGoal(root,id,patch={}){const s=read(root),g=s.goals.find(x=>x.id===id);if(!g)throw Error('goal not found');if(patch.status&&['active','paused','complete'].includes(patch.status))g.status=patch.status;if(patch.target)g.target=metrics(patch.target);g.updatedAt=new Date().toISOString();write(root,s);return g}
export function channelGoalProgress(goal,performance={top:[]},publishJobs=[]){const rows=(performance.top||[]).filter(x=>(goal.platform==='all'||(x.platforms||[]).includes(goal.platform))&&(goal.niche==='all'||x.niche===goal.niche));const actual={views:rows.reduce((n,x)=>n+Number(x.views||0),0),watchMinutes:rows.reduce((n,x)=>n+Number(x.watchMinutes||0),0),published:publishJobs.filter(j=>j.status==='published'&&(goal.platform==='all'||j.platform===goal.platform)).length,subscribers:rows.reduce((n,x)=>n+Number(x.subscribers||0),0)};const progress={};for(const k of Object.keys(goal.target||{}))progress[k]=goal.target[k]?Math.min(999,Number((100*actual[k]/goal.target[k]).toFixed(1))):null;return {goalId:goal.id,target:goal.target,actual,progress,observedProjects:rows.length,policy:{observedMetricsOnly:true,guarantee:false}}}
