import fs from 'node:fs';
import path from 'node:path';
const file=root=>path.join(root,'creative-memory.json');
const read=root=>{try{return JSON.parse(fs.readFileSync(file(root),'utf8'))}catch{return {version:1,items:[],updatedAt:null}}};
const write=(root,state)=>{fs.mkdirSync(root,{recursive:true});const f=file(root),tmp=f+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state,null,2),{mode:0o600});fs.renameSync(tmp,f);return state};
const hook=s=>{const x=String(s||'').toLowerCase();if(/\?|why|how|what/.test(x))return 'question';if(/secret|hidden|truth|unknown/.test(x))return 'curiosity';if(/mistake|wrong|never|avoid|warning/.test(x))return 'risk';if(/\d|top |best |worst /.test(x))return 'list';return 'statement'};
export function refreshCreativeMemory(root,projects=[],performance={top:[]},experiments={winners:[]}){const perf=new Map((performance.top||[]).map(x=>[x.projectId,x])),items=[];for(const p of projects){const r=perf.get(p.id);if(!r)continue;const title=String(p.publish?.title||p.topic||'');items.push({projectId:p.id,niche:p.niche||'general',style:p.style||'unknown',hook:hook(title),titleWords:title.trim().split(/\s+/).filter(Boolean).length,views:Number(r.views||0),watchMinutes:Number(r.watchMinutes||0),performanceScore:Number(r.score||0),platforms:r.platforms||[],observedAt:new Date().toISOString()})}for(const w of experiments.winners||[])if(w.status==='complete')items.push({projectId:w.projectId,type:`experiment-${w.type}`,value:String(w.value||'').slice(0,240),ctr:Number(w.ctr||0),impressions:Number(w.impressions||0),confidence:w.confidence||'early',observedAt:new Date().toISOString()});items.sort((a,b)=>(b.performanceScore||0)-(a.performanceScore||0)||(b.impressions||0)-(a.impressions||0));return write(root,{version:1,items:items.slice(0,300),updatedAt:new Date().toISOString(),policy:{observedMetricsOnly:true,copyExactWinner:false,ownerReviewRequired:true}})}
export function readCreativeMemory(root){return read(root)}
export function retrieveCreativeMemory(root,{niche='',style='',limit=6}={}){const state=read(root),rows=(state.items||[]).filter(x=>(!niche||x.niche===niche)&&(!style||x.style===style)).slice(0,Math.max(1,Math.min(20,Number(limit||6))));return {updatedAt:state.updatedAt,items:rows,policy:state.policy||{observedMetricsOnly:true,copyExactWinner:false,ownerReviewRequired:true}}}
