import { readGoogleOAuthStore, writeGoogleOAuthStore } from './google-oauth.mjs';

export function saveGoogleOAuthClientAuthenticated(root,{clientId,clientSecret,ownerEmail}){
  const id=String(clientId||'').trim(),secret=String(clientSecret||'').trim(),email=String(ownerEmail||'').trim().toLowerCase();
  if(id.length<20||secret.length<8)throw new Error('Google OAuth client credentials are incomplete');
  if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Owner email is invalid');
  const store=readGoogleOAuthStore(root);store.oauthClient={clientId:id,clientSecret:secret,ownerEmails:email?[email]:[],configuredAt:new Date().toISOString()};writeGoogleOAuthStore(root,store);
  return {configured:true,ownerEmailConfigured:!!email};
}

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export function googleSetupPage({error=''}={}){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Google Setup · Viral Shorts Studio</title><style>body{font-family:system-ui;background:#0b0d12;color:#fff;display:grid;place-items:center;min-height:100vh;margin:0}.card{width:min(520px,calc(100% - 36px));background:#11151d;border:1px solid #2a3140;border-radius:18px;padding:24px}input,button{width:100%;box-sizing:border-box;padding:13px;margin-top:10px;border-radius:10px;border:1px solid #31394b}input{background:#0d1118;color:#fff}button{font-weight:800}.muted{color:#9aa6ba}.err{color:#ff9d9d}.ok{color:#85f5a3}</style></head><body><form class="card" method="post" action="/setup/google" autocomplete="off"><h2>Connect Google</h2><p class="muted">Credentials go directly from this browser to your VPS and are stored only in the protected application data volume. This page is protected by your owner session and is not publicly accessible.</p>${error?`<p class="err">${esc(error)}</p>`:''}<label>Google OAuth Client ID<input name="clientId" required autocapitalize="off" spellcheck="false"></label><label>Google OAuth Client Secret<input name="clientSecret" type="password" required autocomplete="new-password"></label><label>Owner Google email<input name="ownerEmail" type="email" required autocomplete="email"></label><button type="submit">Save securely & continue</button></form></body></html>`;}
export function googleSetupSuccessPage(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Google connected</title><style>body{font-family:system-ui;background:#0b0d12;color:#fff;display:grid;place-items:center;min-height:100vh}.card{max-width:480px;background:#11151d;border:1px solid #2a3140;border-radius:18px;padding:24px}.ok{color:#85f5a3}a{display:block;text-align:center;padding:13px;border-radius:10px;background:white;color:#111;text-decoration:none;font-weight:800;margin-top:16px}</style></head><body><div class="card"><h2 class="ok">Google OAuth saved securely</h2><p>Continue with Google to pair your owner identity and sign in. You can return to this protected setup page later to rotate the OAuth client if needed.</p><a href="/api/oauth/google/login">Continue with Google</a></div></body></html>`;}
