import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import { spawnSync } from 'node:child_process';
const f=r=>path.join(r,'product-studio.json');const types=new Set(['ebook','planner','spreadsheet','tracker','lead-magnet']);
function read(r){try{return JSON.parse(fs.readFileSync(f(r),'utf8'))}catch{return {products:[]}}}function write(r,x){fs.mkdirSync(r,{recursive:true});const t=f(r)+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2),{mode:0o600});fs.renameSync(t,f(r))}
const helper=()=>process.env.EXPORT_HELPER||new URL('../python/export_artifacts.py',import.meta.url).pathname;
function persist(r,item){const x=read(r),i=(x.products||[]).findIndex(v=>v.id===item.id);if(i>=0)x.products[i]=item;else x.products=[item,...(x.products||[])].slice(0,200);write(r,x);return item}
export function listProducts(r){return read(r).products||[]}
export function getProduct(r,id){return (read(r).products||[]).find(x=>x.id===id)||null}
export function createProduct(r,i={}){const title=String(i.title||'').trim().slice(0,160);if(title.length<3)throw Error('product title is required');const type=types.has(i.type)?i.type:'ebook',audience=String(i.audience||'').trim().slice(0,400),brand=i.brand&&typeof i.brand==='object'?{name:String(i.brand.name||'').slice(0,120),palette:String(i.brand.palette||'').slice(0,200),version:Number(i.brand.version||0)}:null;const p={id:crypto.randomUUID(),type,title,audience,status:'draft',createdAt:new Date().toISOString(),outline:[`Why ${title} matters`,`Core framework for ${title}`,'Practical implementation','Checklist and next steps'],brand,generation:{policy:'free-only',formats:type==='spreadsheet'||type==='tracker'?['xlsx','csv']:['pdf','docx']},exports:{},exportHistory:[]};persist(r,p);return generateProductExports(r,p.id)}
export function generateProductExports(r,id){const p=getProduct(r,id);if(!p)throw Error('product not found');const dir=path.join(r,'exports','products',p.id);fs.mkdirSync(dir,{recursive:true});const spec=path.join(dir,'spec.json');fs.writeFileSync(spec,JSON.stringify(p,null,2),{mode:0o600});const proc=spawnSync('python3',[helper(),'product',spec,dir],{encoding:'utf8',timeout:30000});if(proc.status!==0)throw Error(`product export failed: ${String(proc.stderr||'').slice(0,240)}`);const exports=JSON.parse(String(proc.stdout||'{}').trim()||'{}'),stamp=new Date().toISOString();return persist(r,{...p,status:'ready',exports,exportHistory:[...(p.exportHistory||[]),{at:stamp,formats:Object.keys(exports)}].slice(-20),updatedAt:stamp})}
