import assert from 'node:assert/strict';
import { normalizeSceneSpec, buildProviderPrompt, sceneVariantTarget, sceneRepairDirective, promptFingerprint } from './scene-render-intelligence.mjs';
import { buildAiGenerationPlan } from './ai-generation-manager.mjs';
const project={topic:'Roman engineering',style:'cinematic',aspect:'16:9',visualContinuity:'same archaeologist and warm stone palette',storyboard:[{index:1,beat:'hook',durationHint:4,shotType:'close-up',searchQuery:'Roman aqueduct collapse',narration:'A hidden weakness could bring an aqueduct down.',motionPrompt:'slow push in'},{index:2,beat:'context',durationHint:5,searchQuery:'Roman aqueduct valley',narration:'The structure crossed valleys for miles.'},{index:3,beat:'payoff',durationHint:4,searchQuery:'Roman concrete channel',narration:'The answer was hidden inside the material itself.'}],scenes:[{index:1,candidateScore:61},{index:2,candidateScore:90,hasRealVideo:true},{index:3,candidateScore:70}],sceneVariants:{'1':[{candidateScore:66}]}};
const spec=normalizeSceneSpec(project.storyboard[0],project);assert.equal(spec.style,'cinematic');assert.equal(spec.aspect,'16:9');assert.match(spec.continuity,/archaeologist/);assert.ok(spec.negative.includes('watermark'));
const built=buildProviderPrompt(project.storyboard[0],project,{provider:'higgsfield'});assert.match(built.prompt,/Subject:/);assert.match(built.prompt,/Continuity:/);assert.match(built.prompt,/Avoid:/);assert.ok(built.prompt.length<=1200);assert.equal(promptFingerprint(built.prompt).length,16);
assert.equal(sceneVariantTarget({beat:'hook'},60),3);assert.equal(sceneVariantTarget({beat:'context'},90),1);assert.match(sceneRepairDirective({}, {visualScore:60,continuity:false,textRisk:true}),/continuity/);
const plan=buildAiGenerationPlan(project,{allowance:2,maxScenes:2,minScore:82,provider:'higgsfield',providerKind:'video'});assert.deepEqual(plan.selected.map(x=>x.index),[1,3]);assert.equal(plan.selected[0].renderSpec.style,'cinematic');assert.equal(plan.selected[0].variantsTarget,3);assert.equal(plan.selected[0].promptFingerprint.length,16);assert.equal(plan.skipped.length,1);
console.log('scene render intelligence tests: ok');
