import crypto from 'node:crypto';

const COOKIE='vss_session';
export const authConfigured=secret=>String(secret||'').length>=24;
export function assertLaunchSecurity({publicLaunch=false,secret=''}={}){if(publicLaunch&&!authConfigured(secret))throw new Error('PUBLIC_LAUNCH requires APP_AUTH_SECRET with at least 24 characters');return true;}
export function ownerSessionToken(secret){return crypto.createHmac('sha256',String(secret)).update('viral-shorts-owner-v1').digest('base64url');}
export function safeEqual(a,b){const A=Buffer.from(String(a||'')),B=Buffer.from(String(b||''));return A.length===B.length&&A.length>0&&crypto.timingSafeEqual(A,B);}
function cookies(req){return Object.fromEntries(String(req.headers?.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));}
export function isOwner(req,secret){return !authConfigured(secret)||safeEqual(cookies(req)[COOKIE],ownerSessionToken(secret));}
export function securityHeaders(req,res,next){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");next();}
export function createRateLimiter({windowMs=300000,max=120}={}){const buckets=new Map();return (req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const now=Date.now(),key=String(req.ip||req.socket?.remoteAddress||'unknown'),old=buckets.get(key);const b=!old||now-old.start>=windowMs?{start:now,count:0}:old;b.count++;buckets.set(key,b);if(buckets.size>1000)for(const [k,v] of buckets)if(now-v.start>=windowMs)buckets.delete(k);res.setHeader('RateLimit-Limit',String(max));res.setHeader('RateLimit-Remaining',String(Math.max(0,max-b.count)));if(b.count>max)return res.status(429).json({error:'Too many write requests; retry shortly'});next();};}
export function loginPage(error=false,{googleEnabled=false,googleError=false,recoveryEnabled=false}={}){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Viral Shorts Studio Login</title><style>body{font-family:system-ui;background:#0b0d12;color:#fff;display:grid;place-items:center;min-height:100vh;margin:0}.card{width:min(380px,calc(100% - 40px));background:#11151d;border:1px solid #2a3140;border-radius:18px;padding:24px}input,button,.google{width:100%;box-sizing:border-box;padding:13px;margin-top:12px;border-radius:10px;border:1px solid #31394b}input{background:#0d1118;color:#fff}button,.google{font-weight:800}.google{display:block;text-align:center;text-decoration:none;background:#fff;color:#111}.or{text-align:center;color:#8e99ad;margin:14px 0 2px}.err{color:#ff9d9d}a{color:#a9c7ff}</style></head><body><form class="card" method="post" action="/api/session"><h2>Viral Shorts Studio</h2><p>Owner access</p>${error?'<p class="err">Incorrect password.</p>':''}${googleError?'<p class="err">Google sign-in was not authorized.</p>':''}${googleEnabled?'<a class="google" href="/api/oauth/google/login">Continue with Google</a><div class="or">or use owner password</div>':''}<input name="password" type="password" autocomplete="current-password" required ${googleEnabled?'':'autofocus'}><button type="submit">Sign in</button>${recoveryEnabled?'<p style="text-align:center;margin-top:16px"><a href="/recover-owner">Forgot owner password?</a></p>':''}</form></body></html>`;}
export function setOwnerCookie(req,res,secret){const secure=String(process.env.FORCE_SECURE_COOKIE||'').toLowerCase()==='true'||req.secure||String(req.get?.('x-forwarded-proto')||'').toLowerCase()==='https';res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(ownerSessionToken(secret))}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${secure?'; Secure':''}`);}
export function clearOwnerCookie(res){res.setHeader('Set-Cookie',`${COOKIE}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`);}
