import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createProviderJob, getProviderJob, resolveProviderJob, failProviderJob } from './provider-job-router.mjs';
import { buildAiGenerationPlan } from './ai-generation-manager.mjs';
import { isPublicHttps } from './url-safety.mjs';

const root=fs.mkdtempSync(path.join(os.tmpdir(),'viral-shorts-test-'));
assert.equal(isPublicHttps('https://example.com/a.mp4'),true);
for(const u of ['http://example.com/a','https://127.0.0.1/a','https://169.254.169.254/a','https://10.0.0.1/a','https://[::1]/a','https://localhost/a'])assert.equal(isPublicHttps(u),false,u);
const job=createProviderJob(root,{provider:'higgsfield',projectId:'p1',sceneIndex:1,kind:'video',verifiedFree:true,prompt:'test'});
assert.equal(job.status,'pending');
assert.throws(()=>resolveProviderJob(root,job.id,{url:'http://example.com/a.mp4'}));
assert.throws(()=>resolveProviderJob(root,job.id,{url:'https://127.0.0.1/a.mp4'}));
assert.throws(()=>resolveProviderJob(root,job.id,{url:'https://example.com/a.mp4',kind:'audio'}));
assert.equal(getProviderJob(root,job.id).status,'pending');
const ready=resolveProviderJob(root,job.id,{url:'https://example.com/a.mp4',kind:'video'});
assert.equal(ready.status,'ready');
assert.equal(ready.resultKind,'video');
const failed=createProviderJob(root,{provider:'nvidia',projectId:'p1',sceneIndex:2,kind:'image',verifiedFree:true});
failProviderJob(root,failed.id,'no quota');
assert.throws(()=>resolveProviderJob(root,failed.id,{url:'https://example.com/a.jpg'}));
const project={storyboard:[{index:1,beat:'hook',durationHint:4},{index:2,beat:'context',durationHint:4},{index:3,beat:'payoff',durationHint:4}],scenes:[{index:1,candidateScore:60},{index:2,candidateScore:90},{index:3,candidateScore:70}]};
const plan=buildAiGenerationPlan(project,{allowance:2,maxScenes:2,minScore:82,provider:'higgsfield'});
assert.deepEqual(plan.selected.map(x=>x.index),[1,3]);
assert.equal(plan.freeOnly,true);assert.equal(plan.paidFallback,false);
fs.rmSync(root,{recursive:true,force:true});
console.log('self-test: ok');