import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createProviderJob, getProviderJob, resolveProviderJob, failProviderJob, claimProviderJobs, releaseProviderJob, reconcileProviderJobs, providerJobStatus } from './provider-job-router.mjs';
import { buildAiGenerationPlan } from './ai-generation-manager.mjs';
import { isPublicHttps } from './url-safety.mjs';
import { recordFreeEvidence, providerEvidence, consumeFreeAllowance, evidenceFresh } from './provider-verifier.mjs';
import { registerLocalAiCandidate } from './ai-candidate-router.mjs';
import { providerWorkerInventory } from './provider-adapters.mjs';
import { preferredOpenRouterFreeModels } from './openrouter-catalog.mjs';
import { pickCloudModel, textModelCatalog } from './text-model-policy.mjs';
import { chooseFreeProvider, freeProviderSummary } from './provider-selector.mjs';
import { sourceQuality, rankSources, rankFacts, narrationQuality, sceneAcceptance } from './content-quality.mjs';

const root=fs.mkdtempSync(path.join(os.tmpdir(),'viral-shorts-test-'));
const sampleSources=[{title:'Great Smog of London',url:'https://example.com/1',extract:'The Great Smog of London occurred in December 1952 and caused thousands of deaths.',provider:'wikipedia'},{title:'Unrelated',url:'https://example.com/2',extract:'A short generic sentence about another topic.',provider:'web'}];
assert.ok(sourceQuality('Great Smog London',sampleSources[0])>sourceQuality('Great Smog London',sampleSources[1]));
assert.equal(rankSources('Great Smog London',sampleSources)[0].title,'Great Smog of London');
assert.ok(Array.isArray(rankFacts('Great Smog London',rankSources('Great Smog London',sampleSources))));
assert.ok(narrationQuality('But one hidden detail changed how London responded.',{beat:'hook'})>=70);
assert.equal(sceneAcceptance(80,'hook').accepted,true);assert.equal(sceneAcceptance(60,'context').accepted,false);
assert.ok(Array.isArray(preferredOpenRouterFreeModels(3)));
const catalog=textModelCatalog();assert.ok(catalog.ollama.length>=3);assert.ok(catalog.huggingface.length>=4);assert.equal(pickCloudModel('ollama',{task:'storyboard',quality:'strong'}),'gpt-oss:120b-cloud');assert.equal(pickCloudModel('huggingface',{task:'storyboard',quality:'balanced'}),'openai/gpt-oss-20b');
assert.equal(isPublicHttps('https://example.com/a.mp4'),true);
for(const u of ['http://example.com/a','https://127.0.0.1/a','https://169.254.169.254/a','https://10.0.0.1/a','https://[::1]/a','https://localhost/a'])assert.equal(isPublicHttps(u),false,u);
const job=createProviderJob(root,{provider:'higgsfield',projectId:'p1',sceneIndex:1,kind:'video',verifiedFree:true,prompt:'test',priority:90});
assert.equal(job.status,'pending');assert.equal(job.priority,90);
const leased=claimProviderJobs(root,{provider:'higgsfield',limit:1,workerId:'test-worker',leaseSeconds:30});
assert.equal(leased.length,1);assert.equal(leased[0].status,'leased');assert.equal(leased[0].attempts,1);
const released=releaseProviderJob(root,job.id,'temporary');assert.equal(released.status,'pending');
assert.throws(()=>resolveProviderJob(root,job.id,{url:'http://example.com/a.mp4'}));
assert.throws(()=>resolveProviderJob(root,job.id,{url:'https://127.0.0.1/a.mp4'}));
assert.throws(()=>resolveProviderJob(root,job.id,{url:'https://example.com/a.mp4',kind:'audio'}));
assert.equal(getProviderJob(root,job.id).status,'pending');
const ready=resolveProviderJob(root,job.id,{url:'https://example.com/a.mp4',kind:'video'});assert.equal(ready.status,'ready');
const failed=createProviderJob(root,{provider:'nvidia',projectId:'p1',sceneIndex:2,kind:'image',verifiedFree:true});
failProviderJob(root,failed.id,'no quota');
assert.throws(()=>resolveProviderJob(root,failed.id,{url:'https://example.com/a.jpg'}));
const exp=createProviderJob(root,{provider:'external',projectId:'p2',sceneIndex:1,kind:'image',verifiedFree:true,ttlSeconds:300});
const ef=path.join(root,'provider-jobs',`${exp.id}.json`),er=JSON.parse(fs.readFileSync(ef,'utf8'));er.expiresAt=new Date(Date.now()-1000).toISOString();fs.writeFileSync(ef,JSON.stringify(er));
reconcileProviderJobs(root);assert.equal(getProviderJob(root,exp.id).status,'expired');
const assetDir=path.join(root,'provider-assets','huggingface');fs.mkdirSync(assetDir,{recursive:true});const asset=path.join(assetDir,'x.jpg');fs.writeFileSync(asset,'x');
const local=registerLocalAiCandidate(root,'p-local',1,{provider:'huggingface',kind:'image',localFile:asset,verifiedFree:true,jobId:'local1'});assert.equal(local.localFile,asset);
assert.throws(()=>registerLocalAiCandidate(root,'p-local',2,{provider:'huggingface',kind:'image',localFile:'/tmp/nope.jpg',verifiedFree:true}));
const inv=providerWorkerInventory(root);assert.equal(inv.find(x=>x.id==='higgsfield').connectorOnly,true);
const ev=recordFreeEvidence(root,{provider:'higgsfield',remaining:2,zeroCost:true,source:'test',evidence:'free allowance',ttlSeconds:300});assert.equal(ev.zeroCostVerified,true);assert.equal(evidenceFresh(ev),true);
assert.equal(chooseFreeProvider(root,'auto').id,'higgsfield');assert.equal(freeProviderSummary(root).selected,'higgsfield');
const after=consumeFreeAllowance(root,'higgsfield',1);assert.equal(after.remaining,1);assert.equal(providerEvidence(root,'higgsfield').remaining,1);
const project={storyboard:[{index:1,beat:'hook',durationHint:4},{index:2,beat:'context',durationHint:4},{index:3,beat:'payoff',durationHint:4}],scenes:[{index:1,candidateScore:60},{index:2,candidateScore:90},{index:3,candidateScore:70}]};
const plan=buildAiGenerationPlan(project,{allowance:2,maxScenes:2,minScore:82,provider:'higgsfield',providerKind:'video'});
assert.deepEqual(plan.selected.map(x=>x.index),[1,3]);
assert.equal(plan.freeOnly,true);assert.equal(plan.paidFallback,false);
const status=providerJobStatus(root);assert.equal(status.counts.ready,1);assert.equal(status.counts.failed,1);assert.equal(status.counts.expired,1);
const {writePhraseCaptions}=await import('./pipeline.mjs');
const captionFile=path.join(root,'phrase-captions.srt');writePhraseCaptions(captionFile,'One two three four five six seven eight',4,{wordsPerCue:4});
const captionText=fs.readFileSync(captionFile,'utf8');assert.match(captionText,/00:00:00,000 --> 00:00:02,000/);assert.match(captionText,/One two three four/);assert.match(captionText,/five six seven eight/);
fs.rmSync(root,{recursive:true,force:true});
console.log('self-test: ok');
