import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const file=root=>path.join(root,'workspace-members.json');
const MEMBER_COOKIE='cos_member';
const digest=s=>crypto.createHash('sha256').update(String(s||'')).digest('hex');
const read=root=>{try{return JSON.parse(fs.readFileSync(file(root),'utf8'))}catch{return {version:1,members:[],invites:[]}}};
const write=(root,state)=>{fs.mkdirSync(root,{recursive:true});const f=file(root),tmp=f+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state,null,2),{mode:0o600});fs.renameSync(tmp,f);return state};
const safe=x=>Object.fromEntries(Object.entries(x).filter(([k])=>!['tokenDigest','inviteDigest'].includes(k)));
export function listWorkspaceMembers(root){const s=read(root);return {members:s.members.map(safe),invites:s.invites.map(safe)}}
export function createWorkspaceInvite(root,input={}){const role=['editor','reviewer'].includes(input.role)?input.role:'reviewer',email=String(input.email||'').trim().toLowerCase().slice(0,180),name=String(input.name||email||'Collaborator').trim().slice(0,100);if(!email.includes('@'))throw Error('valid invite email is required');const raw=`cwi_${crypto.randomBytes(32).toString('base64url')}`,now=new Date().toISOString(),ttlHours=Math.max(1,Math.min(168,Number(input.ttlHours||48))),item={id:crypto.randomUUID(),email,name,role,inviteDigest:digest(raw),createdAt:now,expiresAt:new Date(Date.now()+ttlHours*3600000).toISOString(),acceptedAt:null,revokedAt:null};const s=read(root);s.invites=[item,...s.invites].slice(0,200);write(root,s);return {inviteToken:raw,invite:safe(item)}}
export function acceptWorkspaceInvite(root,raw){const s=read(root),hash=digest(raw),now=Date.now(),invite=s.invites.find(x=>x.inviteDigest===hash&&!x.revokedAt&&!x.acceptedAt&&Date.parse(x.expiresAt)>now);if(!invite)throw Error('invite is invalid or expired');const token=`cwm_${crypto.randomBytes(32).toString('base64url')}`,member={id:crypto.randomUUID(),email:invite.email,name:invite.name,role:invite.role,tokenDigest:digest(token),createdAt:new Date().toISOString(),revokedAt:null};invite.acceptedAt=member.createdAt;invite.memberId=member.id;s.members=[member,...s.members].slice(0,200);write(root,s);return {memberToken:token,member:safe(member)}}
export function revokeWorkspaceMember(root,id){const s=read(root),m=s.members.find(x=>x.id===id);if(!m)throw Error('member not found');m.revokedAt=new Date().toISOString();write(root,s);return safe(m)}
export function verifyWorkspaceMember(root,raw){if(!raw)return null;const hash=digest(raw),m=read(root).members.find(x=>!x.revokedAt&&x.tokenDigest===hash);return m?safe(m):null}
export function memberCanAccess(member,method,pathName){if(!member)return false;const methodUpper=String(method||'GET').toUpperCase(),p=String(pathName||'');const ownerOnly=['/api/workspace','/api/integration-keys','/setup/google','/api/oauth/google','/api/provider-verification/evidence'];if(ownerOnly.some(x=>p.startsWith(x)))return false;if(methodUpper==='GET'||methodUpper==='HEAD')return true;if(member.role==='reviewer')return /^\/api\/projects\/[^/]+\/publish-approval$/.test(p)||/^\/api\/growth\/items\/[^/]+\/decision$/.test(p);if(member.role==='editor'){if(methodUpper==='DELETE')return false;if(/^\/api\/projects\/[^/]+\/publish-approval$/.test(p)||/^\/api\/publish-jobs\/[^/]+\/execute$/.test(p))return false;return p.startsWith('/api/');}return false}

function cookies(req){return Object.fromEntries(String(req?.headers?.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));}
export function workspaceMemberTokenFromRequest(req){const bearer=String(req?.headers?.authorization||'').replace(/^Bearer\s+/i,'').trim();return bearer||cookies(req)[MEMBER_COOKIE]||'';}
export function setWorkspaceMemberCookie(req,res,token){const secure=String(process.env.FORCE_SECURE_COOKIE||'').toLowerCase()==='true'||req?.secure||String(req?.get?.('x-forwarded-proto')||'').toLowerCase()==='https';res.append('Set-Cookie',`${MEMBER_COOKIE}=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${secure?'; Secure':''}`);}
export function clearWorkspaceMemberCookie(res){res.append('Set-Cookie',`${MEMBER_COOKIE}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`);}
export function workspaceJoinPage(error=''){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Join Creator OS</title><style>body{font-family:system-ui;background:#0b0d12;color:#fff;display:grid;place-items:center;min-height:100vh;margin:0}.card{width:min(420px,calc(100% - 40px));background:#11151d;border:1px solid #2a3140;border-radius:18px;padding:24px}input,button{width:100%;box-sizing:border-box;padding:13px;margin-top:12px;border-radius:10px;border:1px solid #31394b}input{background:#0d1118;color:#fff}button{font-weight:800;background:#6c5ce7;color:#fff}.err{color:#ff9d9d}</style></head><body><form class="card" method="post" action="/join"><h2>Join Creator OS workspace</h2><p>Enter the one-time invitation token supplied by the workspace owner.</p>${error?`<p class="err">${String(error).replace(/[<>&]/g,'')}</p>`:''}<input name="inviteToken" autocomplete="off" required autofocus><button type="submit">Accept invitation</button></form></body></html>`;}
