import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const file=root=>path.join(root,'workspace-members.json');
const digest=s=>crypto.createHash('sha256').update(String(s||'')).digest('hex');
const read=root=>{try{return JSON.parse(fs.readFileSync(file(root),'utf8'))}catch{return {version:1,members:[],invites:[]}}};
const write=(root,state)=>{fs.mkdirSync(root,{recursive:true});const f=file(root),tmp=f+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state,null,2),{mode:0o600});fs.renameSync(tmp,f);return state};
const safe=x=>Object.fromEntries(Object.entries(x).filter(([k])=>!['tokenDigest','inviteDigest'].includes(k)));
export function listWorkspaceMembers(root){const s=read(root);return {members:s.members.map(safe),invites:s.invites.map(safe)}}
export function createWorkspaceInvite(root,input={}){const role=['editor','reviewer'].includes(input.role)?input.role:'reviewer',email=String(input.email||'').trim().toLowerCase().slice(0,180),name=String(input.name||email||'Collaborator').trim().slice(0,100);if(!email.includes('@'))throw Error('valid invite email is required');const raw=`cwi_${crypto.randomBytes(32).toString('base64url')}`,now=new Date().toISOString(),ttlHours=Math.max(1,Math.min(168,Number(input.ttlHours||48))),item={id:crypto.randomUUID(),email,name,role,inviteDigest:digest(raw),createdAt:now,expiresAt:new Date(Date.now()+ttlHours*3600000).toISOString(),acceptedAt:null,revokedAt:null};const s=read(root);s.invites=[item,...s.invites].slice(0,200);write(root,s);return {inviteToken:raw,invite:safe(item)}}
export function acceptWorkspaceInvite(root,raw){const s=read(root),hash=digest(raw),now=Date.now(),invite=s.invites.find(x=>x.inviteDigest===hash&&!x.revokedAt&&!x.acceptedAt&&Date.parse(x.expiresAt)>now);if(!invite)throw Error('invite is invalid or expired');const token=`cwm_${crypto.randomBytes(32).toString('base64url')}`,member={id:crypto.randomUUID(),email:invite.email,name:invite.name,role:invite.role,tokenDigest:digest(token),createdAt:new Date().toISOString(),revokedAt:null};invite.acceptedAt=member.createdAt;invite.memberId=member.id;s.members=[member,...s.members].slice(0,200);write(root,s);return {memberToken:token,member:safe(member)}}
export function revokeWorkspaceMember(root,id){const s=read(root),m=s.members.find(x=>x.id===id);if(!m)throw Error('member not found');m.revokedAt=new Date().toISOString();write(root,s);return safe(m)}
export function verifyWorkspaceMember(root,raw){if(!raw)return null;const hash=digest(raw),m=read(root).members.find(x=>!x.revokedAt&&x.tokenDigest===hash);return m?safe(m):null}
export function memberCanAccess(member,method,pathName){if(!member)return false;const methodUpper=String(method||'GET').toUpperCase(),p=String(pathName||'');const ownerOnly=['/api/workspace','/api/integrations','/setup/google','/api/oauth/google','/api/provider-verification/evidence'];if(ownerOnly.some(x=>p.startsWith(x)))return false;if(methodUpper==='GET'||methodUpper==='HEAD')return true;if(member.role==='reviewer')return /^\/api\/projects\/[^/]+\/publish-approval$/.test(p)||/^\/api\/growth\/items\/[^/]+\/decision$/.test(p);if(member.role==='editor'){if(methodUpper==='DELETE')return false;if(/^\/api\/projects\/[^/]+\/publish-approval$/.test(p)||/^\/api\/publish-jobs\/[^/]+\/execute$/.test(p))return false;return p.startsWith('/api/');}return false}
