import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const server=read('app/server.mjs'),pipeline=read('app/pipeline.mjs'),docker=read('Dockerfile'),plan=read('V3_DEVELOPMENT_PLAN.md'),v4=read('V4_DEVELOPMENT_PLAN.md'),v5=read('V5_DEVELOPMENT_PLAN.md'),v6=read('V6_DEVELOPMENT_PLAN.md'),v7=read('V7_DEVELOPMENT_PLAN.md'),v8=read('V8_DEVELOPMENT_PLAN.md'),v9=read('V9_DEVELOPMENT_PLAN.md'),v10=read('V10_DEVELOPMENT_PLAN.md'),v11=read('V11_DEVELOPMENT_PLAN.md'),v12=read('V12_DEVELOPMENT_PLAN.md'),v13=read('V13_DEVELOPMENT_PLAN.md'),v14=read('V14_DEVELOPMENT_PLAN.md'),v15=read('V15_DEVELOPMENT_PLAN.md'),v16=read('V16_DEVELOPMENT_PLAN.md'),v17=read('V17_DEVELOPMENT_PLAN.md'),performance=read('app/platform-performance.mjs'),series=read('app/content-series.mjs'),thumbnail=read('app/thumbnail-lab.mjs'),performanceAgent=read('app/performance-agent.mjs'),socialAnalytics=read('app/social-analytics.mjs'),experimentEvidence=read('app/experiment-evidence.mjs'),growthForecast=read('app/growth-forecast.mjs'),crossPlatform=read('app/cross-platform-learning.mjs'),orchestrator=read('app/agent-orchestrator.mjs'),handoffs=read('app/agent-handoffs.mjs'),creativeIntel=read('app/creative-intelligence.mjs'),campaignLoop=read('app/campaign-loop.mjs'),decisionEngine=read('app/decision-engine.mjs'),provenance=read('app/recommendation-provenance.mjs'),loopHistory=read('app/loop-history.mjs'),decisionFeedback=read('app/decision-feedback.mjs'),postingTime=read('app/posting-time-intelligence.mjs'),recoveryLoop=read('app/recovery-loop.mjs'),creativeMemory=read('app/creative-memory.mjs'),campaignLearning=read('app/campaign-learning.mjs'),channelGoals=read('app/channel-goals.mjs'),backlog=read('app/decision-backlog.mjs'),creativeDecay=read('app/creative-decay.mjs'),postmortem=read('app/campaign-postmortem.mjs'),evaluation=read('app/recommendation-evaluation.mjs'),backup=read('app/backup-bundle.mjs'),score=read('COMPETITIVE_SCORECARD.md');
const checks=[
  ['scoped MCP integration',server.includes("app.post('/mcp'")],
  ['30-minute production',server.includes('duration>1800')&&pipeline.includes('Math.min(240')],
  ['Opportunity Lab live scan',server.includes("/api/opportunity-lab/live-scan")],
  ['voice catalogue',server.includes("/api/voices")],
  ['thumbnail experiments',server.includes("thumbnail-experiment")],
  ['owner-reviewed winner promotion',server.includes("/api/experiments/:id/promote")&&server.includes('ownerReviewed:true')],
  ['verified-free provider gate',server.includes('canQueueFreeProvider')],
  ['competitive scorecard maintained',score.includes('Competitive Scorecard')&&!score.includes('Planned Opportunity Lab adapters')],
  ['V3 tracked work complete',!/^\s*- \[ \]/m.test(plan)],
  ['campaign operating system',server.includes("/api/campaigns")&&server.includes('campaignSchedule')],
  ['growth autopilot',server.includes("/api/growth/queue")&&server.includes('decideGrowthItem')],
  ['workspace collaboration',server.includes("/api/workspace/invites")&&server.includes('memberCanAccess')],
  ['plugin registry',server.includes("/api/plugins")&&server.includes('pluginForTool')],
  ['recovery manifest',server.includes("/api/backup/manifest")&&server.includes('validateRecoverableState')],
  ['V4 tracked work complete',!/^\s*- \[ \]/m.test(v4)],
  ['content portfolio',server.includes("/api/growth/portfolio")&&server.includes('linkPortfolioProject')],
  ['experiment allocation',server.includes("/api/experiments/allocation")],
  ['monetization intelligence',server.includes("/api/monetization")&&server.includes('monetizationBrief')],
  ['V5 tracked work complete',!/^\s*- \[ \]/m.test(v5)],
  ['agent marketplace',server.includes("/api/agents")&&server.includes('agentGoal')],
  ['operations observability',server.includes("/api/operations")&&server.includes('observabilitySnapshot')],
  ['V6 tracked work complete',!/^\s*- \[ \]/m.test(v6)],
  ['neural multilingual Piper voices',docker.includes('piper-tts==1.8.0')&&pipeline.includes('piperVoiceModels')&&server.includes("piper-ro-mihai")],
  ['TikTok connector guarded',server.includes('tiktokPublisherStatus')&&server.includes('uploadTikTokVideo')],
  ['Instagram connector guarded',server.includes('instagramPublisherStatus')&&server.includes('uploadInstagramReel')&&server.includes('/publish-media/:token')],
  ['safe backup export and restore',server.includes("/api/backup/export")&&server.includes("/api/backup/restore")&&backup.includes('RESTORE SAFE STATE')],
  ['V7 tracked work complete',!/^\s*- \[ \]/m.test(v7)],
  ['V8 tracked work complete',!/^\s*- \[ \]/m.test(v8)],
  ['observed post-performance intelligence',server.includes("/api/performance/youtube/sync")&&performance.includes('observedMetricsOnly')],
  ['performance-aware experiment allocation',server.includes('experimentLifecycleRecommendations')],
  ['V9 tracked work complete',!/^\s*- \[ \]/m.test(v9)],
  ['content series intelligence',server.includes("/api/content-series")&&series.includes('contentSeriesRecommendations')],
  ['performance experiment lifecycle',series.includes('experimentLifecycleRecommendations')&&server.includes('experimentLifecycleRecommendations')],
  ['composed thumbnail variants',thumbnail.includes('drawtext=')&&thumbnail.includes('composition:')],
  ['campaign KPI progress',server.includes("/api/campaigns/:id/kpis")&&server.includes('campaignKpiProgress')],
  ['V10 tracked work complete',!/^\s*- \[ \]/m.test(v10)],
  ['performance-aware creator planning',server.includes('planCreatorGoalWithSignals')&&performanceAgent.includes('observedSignals')],
  ['owner-confirmed series batching',server.includes("/api/content-series/:id/create-batch")&&series.includes('seriesEpisodeBatch')],
  ['performance history trends',performance.includes('performanceTrend')&&server.includes("/api/campaigns/:id/trend")],
  ['verified-free AI thumbnail briefs',server.includes("thumbnail-ai-briefs")&&thumbnail.includes('thumbnailCreativeBriefs')&&server.includes('canQueueFreeProvider')],
  ['guarded social analytics',socialAnalytics.includes('video.list')&&server.includes("/api/performance/tiktok/sync")&&server.includes("/api/performance/instagram/sync")],
  ['V11 tracked work complete',!/^\s*- \[ \]/m.test(v11)],
  ['observed experiment evidence ingestion',server.includes("/api/experiments/:id/observations")&&experimentEvidence.includes('readyToClose')],
  ['cross-platform learning',server.includes("/api/performance/learning")&&crossPlatform.includes('observedMetricsOnly')],
  ['directional growth forecast',growthForecast.includes('guarantee:false')&&server.includes('channelGrowthForecast')],
  ['V12 tracked work complete',!/^\s*- \[ \]/m.test(v12)],
  ['coordinated multi-agent planning',server.includes("/api/creator-agent/team-plan")&&orchestrator.includes('Research Agent')&&handoffs.includes('ensureAgentHandoffs')],
  ['observed creative intelligence',server.includes("/api/creative-intelligence")&&creativeIntel.includes('observedMetricsOnly')],
  ['attributed experiment automation',server.includes("/api/experiments/collect-attributed")&&performance.includes('attribution:')],
  ['V13 tracked work complete',!/^\s*- \[ \]/m.test(v13)],
  ['campaign agent orchestration',server.includes("/api/campaigns/:id/orchestrate")&&orchestrator.includes('coordinatedAgentPlan')],
  ['persistent creative memory',server.includes("/api/creative-memory")&&creativeMemory.includes('copyExactWinner:false')],
  ['experiment assignment validation',server.includes("/api/projects/:id/publish-options")&&server.includes('experiment does not belong to project')],
  ['campaign learning reports',server.includes("/api/campaigns/:id/learning-report")&&campaignLearning.includes('observedMetricsOnly:true')],
  ['executive intelligence dashboard',server.includes("/api/executive-dashboard")],
  ['V14 tracked work complete',!/^\s*- \[ \]/m.test(v14)],
  ['full system operating loop',server.includes("/api/system-loop/plan")&&server.includes("/api/system-loop/run")&&decisionEngine.includes('nextBestActions')],
  ['owner-confirmed campaign scheduling',server.includes("/api/campaigns/:id/auto-schedule")&&campaignLoop.includes('autoPublish:false')],
  ['recommendation provenance',provenance.includes('ownerReviewRequired:true')&&campaignLoop.includes('withProvenance')],
  ['V15 tracked work complete',!/^\s*- \[ \]/m.test(v15)],
  ['owner-confirmed recovery loop',server.includes("/api/system-loop/recover")&&recoveryLoop.includes('recoveryCandidates')],
  ['persistent loop history',server.includes("/api/system-loop/history")&&loopHistory.includes('recordLoopCycle')],
  ['decision feedback learning',server.includes("/api/system-loop/feedback")&&decisionFeedback.includes('advisoryOnly:true')&&decisionEngine.includes('feedbackIsAdvisory:true')],
  ['observed posting-time intelligence',server.includes("/api/system-loop/posting-times")&&postingTime.includes('observedMetricsOnly:true')],
  ['V16 tracked work complete',!/^\s*- \[ \]/m.test(v16)],
  ['channel goals and KPI tracking',server.includes("/api/channel-goals")&&channelGoals.includes('channelGoalProgress')],
  ['accepted decision backlog',server.includes("/api/system-loop/backlog")&&backlog.includes('syncAcceptedDecisions')],
  ['dependency-aware parallel agents',orchestrator.includes('parallelWaves')&&orchestrator.includes('dependencyAware:true')],
  ['campaign postmortems',server.includes("/api/campaigns/:id/postmortem")&&postmortem.includes('buildCampaignPostmortem')],
  ['creative decay detection',server.includes("/api/creative-decay")&&creativeDecay.includes('decaying')],
  ['recommendation self-evaluation',server.includes("/api/system-loop/evaluation")&&evaluation.includes('correlationOnly:true')],
  ['V17 tracked work complete',!/^\s*- \[ \]/m.test(v17)]
];
const failed=checks.filter(x=>!x[1]);for(const [name,ok] of checks)console.log(`${ok?'ok':'FAIL'}: ${name}`);if(failed.length)process.exit(1);
