import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const server=read('app/server.mjs'),pipeline=read('app/pipeline.mjs'),docker=read('Dockerfile'),plan=read('V3_DEVELOPMENT_PLAN.md'),v4=read('V4_DEVELOPMENT_PLAN.md'),v5=read('V5_DEVELOPMENT_PLAN.md'),v6=read('V6_DEVELOPMENT_PLAN.md'),v7=read('V7_DEVELOPMENT_PLAN.md'),v8=read('V8_DEVELOPMENT_PLAN.md'),v9=read('V9_DEVELOPMENT_PLAN.md'),v10=read('V10_DEVELOPMENT_PLAN.md'),v11=read('V11_DEVELOPMENT_PLAN.md'),v12=read('V12_DEVELOPMENT_PLAN.md'),v13=read('V13_DEVELOPMENT_PLAN.md'),v14=read('V14_DEVELOPMENT_PLAN.md'),v15=read('V15_DEVELOPMENT_PLAN.md'),v16=read('V16_DEVELOPMENT_PLAN.md'),v17=read('V17_DEVELOPMENT_PLAN.md'),v18=read('V18_DEVELOPMENT_PLAN.md'),v19=read('V19_DEVELOPMENT_PLAN.md'),v20=read('V20_DEVELOPMENT_PLAN.md'),v21=read('V21_DEVELOPMENT_PLAN.md'),v22=read('V22_DEVELOPMENT_PLAN.md'),v23=read('V23_DEVELOPMENT_PLAN.md'),performance=read('app/platform-performance.mjs'),series=read('app/content-series.mjs'),thumbnail=read('app/thumbnail-lab.mjs'),performanceAgent=read('app/performance-agent.mjs'),socialAnalytics=read('app/social-analytics.mjs'),experimentEvidence=read('app/experiment-evidence.mjs'),growthForecast=read('app/growth-forecast.mjs'),crossPlatform=read('app/cross-platform-learning.mjs'),orchestrator=read('app/agent-orchestrator.mjs'),handoffs=read('app/agent-handoffs.mjs'),creativeIntel=read('app/creative-intelligence.mjs'),campaignLoop=read('app/campaign-loop.mjs'),decisionEngine=read('app/decision-engine.mjs'),provenance=read('app/recommendation-provenance.mjs'),loopHistory=read('app/loop-history.mjs'),decisionFeedback=read('app/decision-feedback.mjs'),postingTime=read('app/posting-time-intelligence.mjs'),recoveryLoop=read('app/recovery-loop.mjs'),creativeMemory=read('app/creative-memory.mjs'),campaignLearning=read('app/campaign-learning.mjs'),channelGoals=read('app/channel-goals.mjs'),backlog=read('app/decision-backlog.mjs'),creativeDecay=read('app/creative-decay.mjs'),postmortem=read('app/campaign-postmortem.mjs'),evaluation=read('app/recommendation-evaluation.mjs'),goalPortfolio=read('app/goal-portfolio.mjs'),outcomeAttribution=read('app/outcome-attribution.mjs'),resourceScheduler=read('app/resource-scheduler.mjs'),commandCenter=read('app/command-center.mjs'),executionJournal=read('app/execution-journal.mjs'),goalRisk=read('app/goal-risk-actions.mjs'),operationalHealth=read('app/operational-health.mjs'),guardedExecution=read('app/guarded-execution.mjs'),executionPreview=read('app/execution-preview.mjs'),executionReconciliation=read('app/execution-reconciliation.mjs'),backup=read('app/backup-bundle.mjs'),score=read('COMPETITIVE_SCORECARD.md');
const checks=[
  ['scoped MCP integration',server.includes("app.post('/mcp'")],
  ['30-minute production',server.includes('duration>1800')&&pipeline.includes('Math.min(240')],
  ['Opportunity Lab live scan',server.includes("/api/opportunity-lab/live-scan")],
  ['voice catalogue',server.includes("/api/voices")],
  ['thumbnail experiments',server.includes("thumbnail-experiment")],
  ['owner-reviewed winner promotion',server.includes("/api/experiments/:id/promote")&&server.includes('ownerReviewed:true')],
  ['verified-free provider gate',server.includes('canQueueFreeProvider')],
  ['competitive scorecard maintained',score.includes('Competitive Scorecard')&&!score.includes('Planned Opportunity Lab adapters')],
  ['V3 tracked work complete',!/^\s*- \[ \]/m.test(plan)],
  ['campaign operating system',server.includes("/api/campaigns")&&server.includes('campaignSchedule')],
  ['growth autopilot',server.includes("/api/growth/queue")&&server.includes('decideGrowthItem')],
  ['workspace collaboration',server.includes("/api/workspace/invites")&&server.includes('memberCanAccess')],
  ['plugin registry',server.includes("/api/plugins")&&server.includes('pluginForTool')],
  ['recovery manifest',server.includes("/api/backup/manifest")&&server.includes('validateRecoverableState')],
  ['V4 tracked work complete',!/^\s*- \[ \]/m.test(v4)],
  ['content portfolio',server.includes("/api/growth/portfolio")&&server.includes('linkPortfolioProject')],
  ['experiment allocation',server.includes("/api/experiments/allocation")],
  ['monetization intelligence',server.includes("/api/monetization")&&server.includes('monetizationBrief')],
  ['V5 tracked work complete',!/^\s*- \[ \]/m.test(v5)],
  ['agent marketplace',server.includes("/api/agents")&&server.includes('agentGoal')],
  ['operations observability',server.includes("/api/operations")&&server.includes('observabilitySnapshot')],
  ['V6 tracked work complete',!/^\s*- \[ \]/m.test(v6)],
  ['neural multilingual Piper voices',docker.includes('piper-tts==1.8.0')&&pipeline.includes('piperVoiceModels')&&server.includes("piper-ro-mihai")],
  ['TikTok connector guarded',server.includes('tiktokPublisherStatus')&&server.includes('uploadTikTokVideo')],
  ['Instagram connector guarded',server.includes('instagramPublisherStatus')&&server.includes('uploadInstagramReel')&&server.includes('/publish-media/:token')],
  ['safe backup export and restore',server.includes("/api/backup/export")&&server.includes("/api/backup/restore")&&backup.includes('RESTORE SAFE STATE')],
  ['V7 tracked work complete',!/^\s*- \[ \]/m.test(v7)],
  ['V8 tracked work complete',!/^\s*- \[ \]/m.test(v8)],
  ['observed post-performance intelligence',server.includes("/api/performance/youtube/sync")&&performance.includes('observedMetricsOnly')],
  ['performance-aware experiment allocation',server.includes('experimentLifecycleRecommendations')],
  ['V9 tracked work complete',!/^\s*- \[ \]/m.test(v9)],
  ['content series intelligence',server.includes("/api/content-series")&&series.includes('contentSeriesRecommendations')],
  ['performance experiment lifecycle',series.includes('experimentLifecycleRecommendations')&&server.includes('experimentLifecycleRecommendations')],
  ['composed thumbnail variants',thumbnail.includes('drawtext=')&&thumbnail.includes('composition:')],
  ['campaign KPI progress',server.includes("/api/campaigns/:id/kpis")&&server.includes('campaignKpiProgress')],
  ['V10 tracked work complete',!/^\s*- \[ \]/m.test(v10)],
  ['performance-aware creator planning',server.includes('planCreatorGoalWithSignals')&&performanceAgent.includes('observedSignals')],
  ['owner-confirmed series batching',server.includes("/api/content-series/:id/create-batch")&&series.includes('seriesEpisodeBatch')],
  ['performance history trends',performance.includes('performanceTrend')&&server.includes("/api/campaigns/:id/trend")],
  ['verified-free AI thumbnail briefs',server.includes("thumbnail-ai-briefs")&&thumbnail.includes('thumbnailCreativeBriefs')&&server.includes('canQueueFreeProvider')],
  ['guarded social analytics',socialAnalytics.includes('video.list')&&server.includes("/api/performance/tiktok/sync")&&server.includes("/api/performance/instagram/sync")],
  ['V11 tracked work complete',!/^\s*- \[ \]/m.test(v11)],
  ['observed experiment evidence ingestion',server.includes("/api/experiments/:id/observations")&&experimentEvidence.includes('readyToClose')],
  ['cross-platform learning',server.includes("/api/performance/learning")&&crossPlatform.includes('observedMetricsOnly')],
  ['directional growth forecast',growthForecast.includes('guarantee:false')&&server.includes('channelGrowthForecast')],
  ['V12 tracked work complete',!/^\s*- \[ \]/m.test(v12)],
  ['coordinated multi-agent planning',server.includes("/api/creator-agent/team-plan")&&orchestrator.includes('Research Agent')&&handoffs.includes('ensureAgentHandoffs')],
  ['observed creative intelligence',server.includes("/api/creative-intelligence")&&creativeIntel.includes('observedMetricsOnly')],
  ['attributed experiment automation',server.includes("/api/experiments/collect-attributed")&&performance.includes('attribution:')],
  ['V13 tracked work complete',!/^\s*- \[ \]/m.test(v13)],
  ['campaign agent orchestration',server.includes("/api/campaigns/:id/orchestrate")&&orchestrator.includes('coordinatedAgentPlan')],
  ['persistent creative memory',server.includes("/api/creative-memory")&&creativeMemory.includes('copyExactWinner:false')],
  ['experiment assignment validation',server.includes("/api/projects/:id/publish-options")&&server.includes('experiment does not belong to project')],
  ['campaign learning reports',server.includes("/api/campaigns/:id/learning-report")&&campaignLearning.includes('observedMetricsOnly:true')],
  ['executive intelligence dashboard',server.includes("/api/executive-dashboard")],
  ['V14 tracked work complete',!/^\s*- \[ \]/m.test(v14)],
  ['full system operating loop',server.includes("/api/system-loop/plan")&&server.includes("/api/system-loop/run")&&decisionEngine.includes('nextBestActions')],
  ['owner-confirmed campaign scheduling',server.includes("/api/campaigns/:id/auto-schedule")&&campaignLoop.includes('autoPublish:false')],
  ['recommendation provenance',provenance.includes('ownerReviewRequired:true')&&campaignLoop.includes('withProvenance')],
  ['V15 tracked work complete',!/^\s*- \[ \]/m.test(v15)],
  ['owner-confirmed recovery loop',server.includes("/api/system-loop/recover")&&recoveryLoop.includes('recoveryCandidates')],
  ['persistent loop history',server.includes("/api/system-loop/history")&&loopHistory.includes('recordLoopCycle')],
  ['decision feedback learning',server.includes("/api/system-loop/feedback")&&decisionFeedback.includes('advisoryOnly:true')&&decisionEngine.includes('feedbackIsAdvisory:true')],
  ['observed posting-time intelligence',server.includes("/api/system-loop/posting-times")&&postingTime.includes('observedMetricsOnly:true')],
  ['V16 tracked work complete',!/^\s*- \[ \]/m.test(v16)],
  ['channel goals and KPI tracking',server.includes("/api/channel-goals")&&channelGoals.includes('channelGoalProgress')],
  ['accepted decision backlog',server.includes("/api/system-loop/backlog")&&backlog.includes('syncAcceptedDecisions')],
  ['dependency-aware parallel agents',orchestrator.includes('parallelWaves')&&orchestrator.includes('dependencyAware:true')],
  ['campaign postmortems',server.includes("/api/campaigns/:id/postmortem")&&postmortem.includes('buildCampaignPostmortem')],
  ['creative decay detection',server.includes("/api/creative-decay")&&creativeDecay.includes('decaying')],
  ['recommendation self-evaluation',server.includes("/api/system-loop/evaluation")&&evaluation.includes('correlationOnly:true')],
  ['V17 tracked work complete',!/^\s*- \[ \]/m.test(v17)],
  ['guarded backlog execution',server.includes("/api/system-loop/backlog/:id/execute")&&server.includes('ownerConfirmed:true')],
  ['goal portfolio command center',server.includes("/api/system-loop/command-center")&&goalPortfolio.includes('atRisk')&&commandCenter.includes('highestValueAction')],
  ['resource-aware agent coordination',resourceScheduler.includes('resourceBounded:true')&&server.includes('AGENT_MAX_PARALLEL')],
  ['correlational outcome attribution',server.includes("/api/system-loop/attribution")&&outcomeAttribution.includes('causalityClaimed:false')],
  ['V18 tracked work complete',!/^\s*- \[ \]/m.test(v18)],
  ['guarded backlog batch execution',server.includes("/api/system-loop/backlog/execute-ready")&&server.includes('maxPerBatch:3')],
  ['persistent execution journal',server.includes("/api/system-loop/executions")&&executionJournal.includes('ownerConfirmed')&&backup.includes('execution-journal.json')],
  ['goal-risk recovery campaigns',server.includes("/api/channel-goals/:id/create-recovery-campaign")&&goalRisk.includes('observed-goal-progress')],
  ['V19 tracked work complete',!/^\s*- \[ \]/m.test(v19)],
  ['stale-work operational health',server.includes("/api/system-loop/health")&&operationalHealth.includes('autoRecover:false')],
  ['idempotent guarded execution',server.includes('completedExecutionForBacklog')&&server.includes('already has a completed execution')],
  ['owner-confirmed maintenance cycle',server.includes("/api/system-loop/maintenance")&&server.includes('projectsAutoRecovered:false')],
  ['V20 tracked work complete',!/^\s*- \[ \]/m.test(v20)],
  ['time-bounded operational failures',operationalHealth.includes('failureWindowMinutes')&&operationalHealth.includes('recentFailures')],
  ['guarded maintenance preview',server.includes("/api/system-loop/maintenance-preview")&&operationalHealth.includes('maintenancePreview')],
  ['V21 tracked work complete',!/^\s*- \[ \]/m.test(v21)],
  ['state-bound maintenance confirmation',operationalHealth.includes('previewToken')&&operationalHealth.includes('maintenancePreviewMatches')&&server.includes('preview is missing or stale')],
  ['health failure window passthrough',server.includes('failureWindowMinutes:Number(req.query.failureWindowMinutes||60)')],
  ['guarded execution validates before claim',server.includes("validateBacklogExecution(item,{loadProject:load});decideBacklogItem(DATA,item.id,'in-progress')")&&guardedExecution.includes('supportedTypes')&&guardedExecution.includes('source project not found')],
  ['guarded execution journals before done',/recordExecution\(DATA,\{backlogId:item\.id,type:item\.type,status:'completed'[\s\S]*?decideBacklogItem\(DATA,item\.id,'done'\)/.test(server)],
  ['bounded guarded batch attempts',server.includes('failedAttemptsConsumeCapacity:true')&&executionPreview.includes('maxPerBatch=3')&&executionPreview.includes('Math.min(maxPerBatch')],
  ['worker token least privilege',server.includes('workerCanAccess(req.method,req.path)')&&server.includes('provider worker token is not permitted for this route')],
  ['integration keys owner only',server.includes("app.post('/api/integration-keys',(req,res)=>{if(req.authActor?.type!=='owner')")&&server.includes("app.delete('/api/integration-keys/:id',(req,res)=>{if(req.authActor?.type!=='owner')")],
  ['provider worker healthcheck',read('compose.yaml').includes('provider-worker-status.json')&&read('compose.yaml').includes('age<90000')],
  ['durable safe backup coverage',backup.includes('content-portfolio.json')&&backup.includes('voice-studio.json')&&backup.includes('regeneratedAfterRestore')],
  ['provider admin owner boundary',server.includes("app.post('/api/provider-jobs/claim',(req,res)=>{if(req.authActor?.type!=='owner')")&&server.includes("app.post('/api/providers/:id/smoke',async(req,res)=>{if(req.authActor?.type!=='owner')")],
  ['worker evidence endpoint retained',read('app/security.mjs').includes("p==='/api/provider-verification/evidence'")],
  ['audit history safe backup',backup.includes('auditEvents')&&backup.includes('audit-log.jsonl')&&backup.includes('checksumPayload')],
  ['text routing learning recoverable',backup.includes('text-router-learning.json')&&read('app/backup-manifest.mjs').includes('text-router-learning.json')],
  ['reproducible container images',read('Dockerfile').includes('node:22-bookworm-slim@sha256:')&&read('compose.yaml').includes('ollama/ollama@sha256:')],
  ['V22 tracked work complete',!/^\s*- \[ \]/m.test(v22)],
  ['state-bound backlog batch execution',server.includes("/api/system-loop/backlog/execute-preview")&&server.includes('execution preview is missing or stale')&&executionPreview.includes('stateBoundConfirmation:true')],
  ['guarded failure state recovery',server.includes("decideBacklogItem(DATA,item.id,output?'done':'ready')")&&server.includes('executionHandled=true')],
  ['execution reconciliation',server.includes("/api/system-loop/executions/reconcile")&&executionReconciliation.includes('autoRepair:false')&&commandCenter.includes('reconciliation')],
  ['V23 tracked work complete',!/^\s*- \[ \]/m.test(v23)]
];
const failed=checks.filter(x=>!x[1]);for(const [name,ok] of checks)console.log(`${ok?'ok':'FAIL'}: ${name}`);if(failed.length)process.exit(1);
